# Generated by Django 5.1.2 on 2025-03-28 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_item',
            name='order',
        ),
        migrations.RemoveField(
            model_name='ordered_item',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Ordered_item',
        ),
    ]
