# Generated by Django 5.1.2 on 2025-03-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0003_order_ordered_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='delivery_date',
            field=models.DateField(default='2025-01-01'),
            preserve_default=False,
        ),
    ]
