# Generated by Django 5.1.2 on 2025-04-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0004_variant_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('p', 'pending'), ('s', 'success')], max_length=1),
        ),
    ]
