# Generated by Django 5.1.2 on 2025-04-01 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0005_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordered_item',
            name='product',
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tannis_app.variant'),
            preserve_default=False,
        ),
    ]
