# Generated by Django 5.1.2 on 2025-04-02 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0006_remove_ordered_item_product_ordered_item_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='o_variants', to='tannis_app.variant'),
        ),
    ]
