# Generated by Django 5.1.2 on 2025-04-02 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0007_alter_ordered_item_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c_variants', to='tannis_app.variant'),
        ),
    ]
