# Generated by Django 5.1.2 on 2025-04-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0008_alter_cartitem_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordered_item',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='tannis_app.order'),
        ),
    ]
