# Generated by Django 5.1.2 on 2025-04-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0009_alter_ordered_item_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
