# Generated by Django 5.1.2 on 2025-04-03 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0010_alter_variant_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='delivery_date',
        ),
    ]
