# Generated by Django 5.1.2 on 2025-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0012_shippingaddress_name_shippingaddress_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='address',
            new_name='country',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address1',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
