# Generated by Django 5.1.2 on 2025-04-16 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0013_rename_address_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
