# Generated by Django 5.1.2 on 2025-04-16 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0015_shippingaddress_email_alter_shippingaddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='type_of_address',
            field=models.CharField(choices=[('home', 'home'), ('work', 'work'), ('other', 'other')], max_length=255),
        ),
    ]
