# Generated by Django 5.1.2 on 2025-04-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0016_alter_shippingaddress_type_of_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='type_of_address',
            field=models.CharField(choices=[('Home', 'Home'), ('Work', 'Work'), ('Other', 'Other')], max_length=255),
        ),
    ]
