# Generated by Django 5.1.2 on 2025-04-19 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0017_alter_shippingaddress_type_of_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(),
        ),
    ]
