# Generated by Django 5.1.2 on 2025-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0018_alter_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('pin_code', models.CharField(max_length=6)),
                ('extra_days', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ordered_item',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='base_shipping_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
