# Generated by Django 5.1.2 on 2025-04-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0019_deliveryzone_ordered_item_expected_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_shipping_days',
        ),
        migrations.AddField(
            model_name='variant',
            name='base_shipping_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
