# Generated by Django 5.1.2 on 2025-04-21 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0020_remove_product_base_shipping_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveryzone',
            old_name='region',
            new_name='city',
        ),
    ]
