# Generated by Django 5.1.2 on 2025-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0021_rename_region_deliveryzone_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
