# Generated by Django 5.1.2 on 2025-05-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0023_shippingaddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='mrp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
