# Generated by Django 5.1.2 on 2025-06-14 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0024_cartitem_mrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
