# Generated by Django 5.1.2 on 2025-07-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0028_rename_order_date_order_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
