# Generated by Django 5.1.2 on 2025-07-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tannis_app', '0029_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
